### totalVI
#environment_matilda
#python main_totalVI.py --path1  "../../../dataset/benchmark_dataset/cross integration/dataset43/rna1.h5"  "../../../dataset/benchmark_dataset/cross integration/dataset43/rna2.h5"  --path2 "../../../dataset/benchmark_dataset/cross integration/dataset43/adt1.h5" "../../../dataset/benchmark_dataset/cross integration/dataset43/adt2.h5" --save_path "../../../result/integrated_embedding/cross integration/dataset43/totalVI/"

python main_totalVI.py --path1  "../../../dataset/benchmark_dataset/cross integration/dataset44/rna1.h5"  "../../../dataset/benchmark_dataset/cross integration/dataset44/rna2.h5"  "../../../dataset/benchmark_dataset/cross integration/dataset44/rna3.h5"  --path2 "../../../dataset/benchmark_dataset/cross integration/dataset44/adt1.h5" "../../../dataset/benchmark_dataset/cross integration/dataset44/adt2.h5"  "../../../dataset/benchmark_dataset/cross integration/dataset44/adt3.h5" --save_path "../../../result/integrated_embedding/cross integration/dataset44/totalVI/"

python main_totalVI.py --path1  "../../../dataset/benchmark_dataset/cross integration/dataset45/rna1.h5"  "../../../dataset/benchmark_dataset/cross integration/dataset45/rna2.h5"  --path2 "../../../dataset/benchmark_dataset/cross integration/dataset45/adt1.h5" "../../../dataset/benchmark_dataset/cross integration/dataset45/adt2.h5" --save_path "../../../result/integrated_embedding/cross integration/dataset45/totalVI/"

python main_totalVI.py --path1  "../../../dataset/benchmark_dataset/cross integration/dataset46/rna1.h5"  "../../../dataset/benchmark_dataset/cross integration/dataset46/rna2.h5"  "../../../dataset/benchmark_dataset/cross integration/dataset46/rna3.h5"  "../../../dataset/benchmark_dataset/cross integration/dataset46/rna4.h5"  "../../../dataset/benchmark_dataset/cross integration/dataset46/rna5.h5"  "../../../dataset/benchmark_dataset/cross integration/dataset46/rna6.h5"  "../../../dataset/benchmark_dataset/cross integration/dataset46/rna7.h5"  "../../../dataset/benchmark_dataset/cross integration/dataset46/rna8.h5"  "../../../dataset/benchmark_dataset/cross integration/dataset46/rna9.h5"  "../../../dataset/benchmark_dataset/cross integration/dataset46/rna10.h5"  "../../../dataset/benchmark_dataset/cross integration/dataset46/rna11.h5"  "../../../dataset/benchmark_dataset/cross integration/dataset46/rna12.h5"  --path2 "../../../dataset/benchmark_dataset/cross integration/dataset46/adt1.h5" "../../../dataset/benchmark_dataset/cross integration/dataset46/adt2.h5" "../../../dataset/benchmark_dataset/cross integration/dataset46/adt3.h5" "../../../dataset/benchmark_dataset/cross integration/dataset46/adt4.h5" "../../../dataset/benchmark_dataset/cross integration/dataset46/adt5.h5" "../../../dataset/benchmark_dataset/cross integration/dataset46/adt6.h5" "../../../dataset/benchmark_dataset/cross integration/dataset46/adt7.h5" "../../../dataset/benchmark_dataset/cross integration/dataset46/adt8.h5" "../../../dataset/benchmark_dataset/cross integration/dataset46/adt9.h5" "../../../dataset/benchmark_dataset/cross integration/dataset46/adt10.h5" "../../../dataset/benchmark_dataset/cross integration/dataset46/adt11.h5" "../../../dataset/benchmark_dataset/cross integration/dataset46/adt12.h5" --save_path "../../../result/integrated_embedding/cross integration/dataset46/totalVI/"

python main_totalVI.py --path1  "../../../dataset/benchmark_dataset/cross integration/dataset47/rna1.h5"  "../../../dataset/benchmark_dataset/cross integration/dataset47/rna2.h5"  --path2 "../../../dataset/benchmark_dataset/cross integration/dataset47/adt1.h5" "../../../dataset/benchmark_dataset/cross integration/dataset47/adt2.h5" --save_path "../../../result/integrated_embedding/cross integration/dataset47/totalVI/"
